Repository HyunjeLee/Scrap-2024, pull requests merged in 2024-04, with the labels that each got.

#6 #3 카테고리 화면 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/scrap/scrap2024/CategoryActivity.kt
  app/src/main/java/com/scrap/scrap2024/CategoryAdapter.kt
  app/src/main/java/com/scrap/scrap2024/LoginActivity.kt
  app/src/main/java/com/scrap/scrap2024/MainActivity.kt
  app/src/main/java/com/scrap/scrap2024/nav/CategoryFragment.kt
  app/src/main/java/com/scrap/scrap2024/nav/FavoriteFragment.kt
  app/src/main/java/com/scrap/scrap2024/nav/MypageFragment.kt
  app/src/main/java/com/scrap/scrap2024/nav/ScrapFragment.kt
  app/src/main/java/com/scrap/scrap2024/nav/SearchFragment.kt
  app/src/main/res/drawable/bg_btn.xml
  app/src/main/res/drawable/category.png
  app/src/main/res/drawable/fab.png
  app/src/main/res/drawable/favorite.png
  app/src/main/res/drawable/menu_click_color.xml
  app/src/main/res/drawable/mypage.png
  app/src/main/res/drawable/nav_round.xml
  app/src/main/res/drawable/scrap.png
  app/src/main/res/drawable/search.png
  app/src/main/res/font/nanum_gothic_bold.ttf
  app/src/main/res/font/nanum_gothic_extra_bold.ttf
  app/src/main/res/font/nanum_gothic_regular.ttf
  app/src/main/res/layout/activity_category.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_category.xml
  app/src/main/res/layout/fragment_favorite.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/layout/fragment_scrap.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/item_category.xml
  app/src/main/res/menu/navi_menu.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: :sparkles: feat

#10 #7 고유색상 추가, 폰트 bold 처리, 배경색 설정
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/drawable/ic_launcher_foreground.xml
  app/src/main/res/drawable/nav_round.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_category.xml
  app/src/main/res/layout/fragment_favorite.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/layout/fragment_scrap.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/item_category.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/themes.xml
Labels: :lipstick: style

#9 #4 카테고리 추가 화면 구현
  .idea/deploymentTargetDropDown.xml
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/scrap/scrap2024/AddCategoryActivity.kt
  app/src/main/java/com/scrap/scrap2024/CategoryAdapter.kt
  app/src/main/java/com/scrap/scrap2024/nav/CategoryFragment.kt
  app/src/main/res/drawable/add_category_bg.png
  app/src/main/res/drawable/bg_button.xml
  app/src/main/res/drawable/bg_edit_add_category.xml
  app/src/main/res/drawable/custom_cursor.xml
  app/src/main/res/drawable/expand_left.png
  app/src/main/res/layout/activity_add_category.xml
  app/src/main/res/layout/fragment_category.xml
  app/src/main/res/layout/item_category.xml
  app/src/main/res/values/strings.xml
Labels: :sparkles: feat

#11 #8 컴포넌트 위치 수정, string soft-coding, 주석 추가
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/scrap/scrap2024/AddCategoryActivity.kt
  app/src/main/java/com/scrap/scrap2024/LoginActivity.kt
  app/src/main/java/com/scrap/scrap2024/MainActivity.kt
  app/src/main/java/com/scrap/scrap2024/nav/CategoryFragment.kt
  app/src/main/java/com/scrap/scrap2024/nav/FavoriteFragment.kt
  app/src/main/java/com/scrap/scrap2024/nav/MypageFragment.kt
  app/src/main/java/com/scrap/scrap2024/nav/ScrapFragment.kt
  app/src/main/java/com/scrap/scrap2024/nav/SearchFragment.kt
  app/src/main/res/drawable/bg_nav_round.xml
  app/src/main/res/drawable/color_nav_click.xml
  app/src/main/res/drawable/nav_category.png
  app/src/main/res/drawable/nav_favorite.png
  app/src/main/res/drawable/nav_mypage.png
  app/src/main/res/drawable/nav_scrap.png
  app/src/main/res/drawable/nav_search.png
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_category.xml
  app/src/main/res/layout/item_category.xml
  app/src/main/res/menu/navi_menu.xml
  app/src/main/res/values/strings.xml
Labels: :hammer_and_wrench: update

#22 PR 템플릿 수정
  .github/pull_request_template.md
Labels: :memo: docs

#21 #20 카테고리-추가하기 에러 토스트 메시지 구현
  app/build.gradle.kts
  app/src/main/java/com/scrap/scrap2024/AddCategoryActivity.kt
  app/src/main/res/layout/activity_add_category.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: :sparkles: feat
